###################################################################

# Created by write_sdc on Mon Nov  1 12:02:01 2021

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports VOUT]
set_load -pin_load 3.40189 [get_ports {DOUT0[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[0]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[0]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[0]}]
create_clock [get_ports CLK]  -name MY_CLK  -period 3.3  -waveform {0 1.65}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports VIN]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports RST_n]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports VOUT]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[0]}]
